# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: blogjou
email: goujou@gmx.de
description: >- # this means to ignore newlines until "baseurl:"
    I am happy about any comments, remarks, critics, or discussions.
    Just send me a mail!
baseurl: "/blogjou" # the subpath of your site, e.g. /blog
url: "goujou.github.io/blogjou" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username: goujou

# Build settings
# theme: jekyll-theme-tactile
theme: minima


plugins:
  - jekyll-paginate
#  - jekyll-feed

feed:
  disable: true

#incremental: true

paginate: 10
paginate_path: "/page:num/"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude:
    - vendor/
    - _code/

show_excerpts: True

header_pages:
    - title: BookJou
      path: book_blog/index.html
      category: book_blog   
    - title: MathJou
      path: math_blog/index.html
      category: math_blog
    - title: PaperJou
      path: paper_blog/index.html
      category: paper_blog
    - title: "Hochzeit"
      path: hochzeit/index.html
      category: hochzeit
    - title: "Matrimonio"
      path: boda/index.html
      category: boda
    - title: "Wedding"
      path: wedding/index.html
      category: wedding
#    - title: PrivateJou
#      path: private_blog/index.html
#      category: private_blog

collections:
  books:
    output: true
  book_authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "books"
    values:
      layout: "book_overview"
      category: "book_blog"
  - scope:
      path: ""
      type: "book_authors"
    values:
      layout: "book_author_overview"
      category: "book_blog"
  - scope:
      path: "book_blog/*"
    values:
      category: "book_blog"
      layout: "book_blog_post"
  - scope:
      path: "math_blog/*"
    values:
      category: "math_blog"
  - scope:
      path: "paper_blog/*"
    values:
      category: "paper_blog"
      layout: "paper_blog_post"
  - scope:
      path: "hochzeit/*"
    values:
      category: "hochzeit"
  - scope:
      path: "boda/*"
    values:
      category: "boda"
  - scope:
      path: "wedding/*"
    values:
      category: "wedding"
  - scope:
      path: "private_blog/*"
    values:
      category: "private_blog"

